### ISSUE TITLE
it doesn't create boxes

### ISSUE THREAD

**Issue by Mscichu** [Wallenstein61/InkScapeBoxMaker#4]
Hey
After install I find in Inkscape 0.92.4 "Box Maker", set the dimensions and press Apply. Appears for 0.5s window "Box Maker" working and disappears. It doesn't generate the shape of the box. How to fix it?

**Comment by Michael-Breu-UIbk** [comment]
Hello Mscichu,

Could you provide me a screenshot with your input parameters, so I can reproduce the problem?

Michael

**Comment by Mscichu** [comment]
![inkscape_makerbox](https://user-images.githubusercontent.com/33583625/51627484-84edf280-1f42-11e9-8204-346dfc5aa4b2.jpg)
As you can see, it doesn't even display the preview. The same is with other box makers. Maybe I need to install some other add-on?
I deleted all Inkscape directories along with extensions, and installed everything again, but still does not create boxes.
I installed Inkscape 32bit and 64bit - no changes.

Dell M6700 Win 8.1 64bit

**Comment by Michael-Breu-UIbk** [comment]
Hello Mscichu,

Sorry to hear, that you still have problems.

I just tried to reproduce your problem on a fresh windows 10 64Bit Machine. However it worked without any problems:

![inkscape1](https://user-images.githubusercontent.com/18215713/51661567-899dbf80-1fb1-11e9-9586-caeaf3b24731.png)

Indeed it should not matter what version (32bit or 64bit) of OS you should use. The extension is written in python, which should be configured automatically along with your inkscape version.

Currently I have no idea, what went wrong. So I have to ask you for some general checks:

1. Are other installed extensions working?

2. Could you check for the presence and correct size of the following files?
![inkscape3](https://user-images.githubusercontent.com/18215713/51662386-f44ffa80-1fb3-11e9-9abc-f9b45818327d.PNG)

2. Could you just activate the logfile under View/Messages (see http://wiki.inkscape.org/wiki/index.php/Debugging_Inkscape#Debugging_Tips_for_Windows). Please check for any unusual output, and attach the log here.
![inkscape2](https://user-images.githubusercontent.com/18215713/51662262-8acfec00-1fb3-11e9-977b-9a86b7d8a4e5.png) (Sorry, the screenshot is for German localization)

Best regards
Michael

**Comment by Mscichu** [comment]
1. Not all:
For example Foldable box works fine
![image](https://user-images.githubusercontent.com/33583625/51681967-7fe27f00-1fe6-11e9-83fd-7a08fb30294f.png)

But Lasercut Box doesn't work
![image](https://user-images.githubusercontent.com/33583625/51682128-e2d41600-1fe6-11e9-846d-115da7c3d6f8.png)

2. Files look good:
![image](https://user-images.githubusercontent.com/33583625/51682199-1878ff00-1fe7-11e9-84b0-879f82359482.png)

3. Nothing appears in the logs using Box Maker:
![image](https://user-images.githubusercontent.com/33583625/51682600-12cfe900-1fe8-11e9-8963-b9dbb4e4cd80.png)

It appears when I use other extensions (Gear for example)
![image](https://user-images.githubusercontent.com/33583625/51682511-e4520e00-1fe7-11e9-97bc-53b67036b4c1.png)

Maybe I have a bad version of Python? How to check?

**Comment by Michael-Breu-UIbk** [comment]
Hello Mscichu,

It seems that you have pulled the most recent GIT Version. Should be identical with the version downloadable from the inkscape-site, but just in case:

Could you download the archive directly from the inkscape site ( https://inkscape.org/gallery/item/13202/BoxMaker_2uBycB2.zip)? Remove the four files above first, unzip the archive to the extensions directory and restart inkscape.

Python is installed alongside with inkscape, so I cannot imagine that it is corrupted.. I have no experience with win8.1 . Could be that there is some incompatibility between inkscape/python/BoxMaker with win8.1

Michael
