### ISSUE TITLE
Name change.

### ISSUE THREAD

**Issue by bbum** [Wallenstein61/InkScapeBoxMaker#5]
This looks really promising.  Unfortunately, the name conflicts with TabbeBoxmaker, which is the most popular box making plugin around.  Both try to install as "boxmaker".

**Comment by Michael-Breu-UIbk** [comment]
Hello bbum,

I just tried to check it. I cannot find TabbeBoxmaker. Did you mean https://inkscape.org/de/~Neon22/%E2%98%85lasercut-tabbed-box .

Or could you provide me with the correct link, to check it myself?

Thankyou
Michael

**Comment by bbum** [comment]
I apologize.  I should have added the link.

https://github.com/paulh-rnd/TabbedBoxMaker

TabbedBoxMaker, a derivative of an early box maker, is the goto tabbed box maker in the GlowForge (and other laser cutters) community.

It is pretty good, if a bit buggy here and there.  And way outdated. 

InkScapeBoxMaker looks like it has a ton of potential!  I look forward to using it.

**Comment by Michael-Breu-UIbk** [comment]
So, I finally change names from boxmaker. py to boxmaker**N**.py, and so on.

So hopefully, naming conflicts will be gone.

Michael

**Comment by bbum** [comment]
Thank you!!!

I'll check out the repository and have a play soon.   Looks very promising!
