### ISSUE TITLE
Overshoot in the top left corner of shelves

### ISSUE THREAD

**Issue by heschlie** [Wallenstein61/InkScapeBoxMaker#7]
When generating a shelved box there seems to be a bit of overshoot to the bounding box in the top left corner of each shelf. Not terribly annoying but does mean extra cutting time on a laser.

Example:

![Screenshot from 2019-06-29 21-32-27](https://user-images.githubusercontent.com/4544262/60392357-a3d64f00-9ab5-11e9-8175-ec2bfe061639.png)

**Comment by Michael-Breu-UIbk** [comment]
Hello Heschlie,

Yes, you are completely correct. 

This is a small inaccuracy in the code.

On our laser cutter setting, this bug costs a fraction of a second extra cutting time and some fraction of a Wh of extra power. To fix this problem costs me an hour of extra work and 3kWh of air condition power. So I prioritized this problem as minor issue.  ;-)

You are more than welcome to support us in development and provide a solution to this.

Cheerio
Wallenstein

**Comment by heschlie** [comment]
@Wallenstein61 it is indeed a very minor inconvenience as mentioned :) and I'm happy to contribute! I'll see if I can find some spare time this week to get a PR up.

**Comment by Michael-Breu-UIbk** [comment]
Since it only a cosmetical flaw, I close this issue now.
