### ISSUE TITLE
Error al hacer click en aplicar

### ISSUE THREAD

**Issue by riopar10** [Wallenstein61/InkScapeBoxMaker#8]
Este error me sale cuando le doy clip en aplicar:
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:311: DeprecationWarning: Effect.OptionParser u 'optparse' ha sido declarado obsoleto y remplazado por 'argparser'. Debe cambiar 'self.OptionParser.add_option’ por 'self.arg_parser.add_argument'; los parámetros son similares.
  self.OptionParser.add_option('--tab',action='store',type='string', dest='tab',default='mm',help='just a dummy')
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:312: DeprecationWarning: Effect.OptionParser u 'optparse' ha sido declarado obsoleto y remplazado por 'argparser'. Debe cambiar 'self.OptionParser.add_option’ por 'self.arg_parser.add_argument'; los parámetros son similares.
  self.OptionParser.add_option('--HingeAndFrame',action='store',type='string', dest='tab',default='mm',help='just a dummy')
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:313: DeprecationWarning: Effect.OptionParser u 'optparse' ha sido declarado obsoleto y remplazado por 'argparser'. Debe cambiar 'self.OptionParser.add_option’ por 'self.arg_parser.add_argument'; los parámetros son similares.
  self.OptionParser.add_option('--Development',action='store',type='string', dest='tab',default='mm',help='just a dummy')
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:315: DeprecationWarning: Effect.OptionParser u 'optparse' ha sido declarado obsoleto y remplazado por 'argparser'. Debe cambiar 'self.OptionParser.add_option’ por 'self.arg_parser.add_argument'; los parámetros son similares.
  self.OptionParser.add_option('--boxType',action='store',type='string', dest='boxType',default='openBox',help='Type of Box')
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:316: DeprecationWarning: Effect.OptionParser u 'optparse' ha sido declarado obsoleto y remplazado por 'argparser'. Debe cambiar 'self.OptionParser.add_option’ por 'self.arg_parser.add_argument'; los parámetros son similares.
  self.OptionParser.add_option('--unit',action='store',type='string', dest='unit',default='mm',help='units of measurement')
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:318: DeprecationWarning: Effect.OptionParser u 'optparse' ha sido declarado obsoleto y remplazado por 'argparser'. Debe cambiar 'self.OptionParser.add_option’ por 'self.arg_parser.add_argument'; los parámetros son similares.
  self.OptionParser.add_option('--box_width',action='store',type='float', dest='boxWidth',default=200.0, help='width of the box.')
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:319: DeprecationWarning: Effect.OptionParser u 'optparse' ha sido declarado obsoleto y remplazado por 'argparser'. Debe cambiar 'self.OptionParser.add_option’ por 'self.arg_parser.add_argument'; los parámetros son similares.
  self.OptionParser.add_option('--box_depth',action='store',type='float', dest='boxDepth',default=120.0, help='depth of the box.')
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:320: DeprecationWarning: Effect.OptionParser u 'optparse' ha sido declarado obsoleto y remplazado por 'argparser'. Debe cambiar 'self.OptionParser.add_option’ por 'self.arg_parser.add_argument'; los parámetros son similares.
  self.OptionParser.add_option('--box_height',action='store',type='float', dest='boxHeight',default=70.0 ,help='height of the box.')
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:321: DeprecationWarning: Effect.OptionParser u 'optparse' ha sido declarado obsoleto y remplazado por 'argparser'. Debe cambiar 'self.OptionParser.add_option’ por 'self.arg_parser.add_argument'; los parámetros son similares.
  self.OptionParser.add_option('--thickness',action='store',type='float', dest='thickness',default=0, help='thickness of the material.')
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:322: DeprecationWarning: Effect.OptionParser u 'optparse' ha sido declarado obsoleto y remplazado por 'argparser'. Debe cambiar 'self.OptionParser.add_option’ por 'self.arg_parser.add_argument'; los parámetros son similares.
  self.OptionParser.add_option('--shelfCount',action='store',type='int', dest='shelfCount',default=1, help='number of shelves.')
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:324: DeprecationWarning: Effect.OptionParser u 'optparse' ha sido declarado obsoleto y remplazado por 'argparser'. Debe cambiar 'self.OptionParser.add_option’ por 'self.arg_parser.add_argument'; los parámetros son similares.
  self.OptionParser.add_option('--frameEdgesMin',action='store',type='float', dest='frameEdgesMin',default=0,help='Minimum distance of frame to edge.')
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:325: DeprecationWarning: Effect.OptionParser u 'optparse' ha sido declarado obsoleto y remplazado por 'argparser'. Debe cambiar 'self.OptionParser.add_option’ por 'self.arg_parser.add_argument'; los parámetros son similares.
  self.OptionParser.add_option('--frameLength',action='store',type='float', dest='frameLength',default=0,help='Length of a frame.')
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:326: DeprecationWarning: Effect.OptionParser u 'optparse' ha sido declarado obsoleto y remplazado por 'argparser'. Debe cambiar 'self.OptionParser.add_option’ por 'self.arg_parser.add_argument'; los parámetros son similares.
  self.OptionParser.add_option('--hingeCircleFactor',action='store',type='float', dest='hingeCircleFactor',default=1.5,help='Size of hinge circle.')
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:328: DeprecationWarning: Effect.OptionParser u 'optparse' ha sido declarado obsoleto y remplazado por 'argparser'. Debe cambiar 'self.OptionParser.add_option’ por 'self.arg_parser.add_argument'; los parámetros son similares.
  self.OptionParser.add_option('--debug',action='store',type='inkbool', dest='debug',default='False',help='debug Info')
boxmakerN.py:29: DeprecationWarning: Effect.affect ahora es 'Effect.run()'. Ha cambiado el argumento 'output'.
  effect.affect()
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:345: DeprecationWarning: Effect.unittouu ahora es un método del documento svg. Utilice 'self.svg.unittouu(str)' en su lugar.
  self.boxWidth = self.unittouu(str(self.options.boxWidth) + unit)
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:346: DeprecationWarning: Effect.unittouu ahora es un método del documento svg. Utilice 'self.svg.unittouu(str)' en su lugar.
  self.boxDepth = self.unittouu(str(self.options.boxDepth) + unit)
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:347: DeprecationWarning: Effect.unittouu ahora es un método del documento svg. Utilice 'self.svg.unittouu(str)' en su lugar.
  self.boxHeight = self.unittouu(str(self.options.boxHeight) + unit)
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:348: DeprecationWarning: Effect.unittouu ahora es un método del documento svg. Utilice 'self.svg.unittouu(str)' en su lugar.
  self.thickness = self.unittouu(str(self.options.thickness) + unit)
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:351: DeprecationWarning: Effect.unittouu ahora es un método del documento svg. Utilice 'self.svg.unittouu(str)' en su lugar.
  self.frameEdgesMin = self.unittouu(str(self.options.frameEdgesMin) + unit)
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:352: DeprecationWarning: Effect.unittouu ahora es un método del documento svg. Utilice 'self.svg.unittouu(str)' en su lugar.
  self.frameLength = self.unittouu(str(self.options.frameLength) + unit)
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:375: DeprecationWarning: Effect.current_layer ahora es un método en svg. Utilice 'self.svg.get_current_layer()' en su lugar.
  self.parent = self.current_layer
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:817: DeprecationWarning: Effect.unittouu ahora es un método del documento svg. Utilice 'self.svg.unittouu(str)' en su lugar.
  style = { 'stroke': color, 'stroke-width': self.unittouu("0.1 mm"), 'font-size':'3px'}
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:818: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  drw = {'style': simplestyle.formatStyle(style), 'x':'%f'%(position.x), 'y':'%f'%(position.y)}
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:819: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"
  textNode = inkex.etree.SubElement(self.parent, inkex.addNS('text', 'svg'), drw)
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:852: DeprecationWarning: Effect.unittouu ahora es un método del documento svg. Utilice 'self.svg.unittouu(str)' en su lugar.
  style = { 'stroke': color, 'fill': 'none', 'stroke-width': self.unittouu("2 mm")}
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:853: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  drw = {'style': simplestyle.formatStyle(style), 'cx':'%f'%center.x, 'cy':'%f'%center.y, 'r':'4' }
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:854: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"
  inkex.etree.SubElement(self.parent, inkex.addNS('circle', 'svg'), drw)
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:856: DeprecationWarning: Effect.unittouu ahora es un método del documento svg. Utilice 'self.svg.unittouu(str)' en su lugar.
  style = { 'stroke': 'black', 'stroke-width': self.unittouu("0.1 mm"), 'font-size':'3px'}
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:857: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  drw = {'style': simplestyle.formatStyle(style), 'x':'%f'%(center.x+5.0), 'y':'%f'%(center.y+5), 'r':'4'}
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:859: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"
  textNode = inkex.etree.SubElement(self.parent, inkex.addNS('text', 'svg'), drw)
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:823: DeprecationWarning: Effect.unittouu ahora es un método del documento svg. Utilice 'self.svg.unittouu(str)' en su lugar.
  style = { 'stroke': color, 'fill': 'none', 'stroke-width': self.unittouu("0.1 mm")}
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:826: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  drw = {'style':simplestyle.formatStyle(style), 'd': actions}
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:827: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"
  edge = inkex.etree.SubElement(self.parent, inkex.addNS('path', 'svg'), drw)
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:830: DeprecationWarning: Effect.unittouu ahora es un método del documento svg. Utilice 'self.svg.unittouu(str)' en su lugar.
  style = { 'stroke': color, 'fill': 'none', 'stroke-width': self.unittouu("0.1 mm")}
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:831: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  drw = {'style':simplestyle.formatStyle(style), 'cx':'%f'%center.x, 'cy':'%f'%center.y, 'r': '%f'%r}
C:\Users\Usuario\AppData\Roaming\inkscape\extensions\boxmakerNLib.py:832: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"
  edge = inkex.etree.SubElement(self.parent, inkex.addNS('circle', 'svg'), drw)
Version de Inkscape - 1.0.2-2 (e86c870879, 2021-01-15
Gracias

**Comment by lpaln** [comment]
These messages are because the extension was never updated for Inkscape 1.0+. I updated it today and it seems to be working okay. I have issued a Pull request, but I am not sure if the original author is monitoring this project anymore. If the original author does not merge the changes, you can use the code from my fork:

https://github.com/lpaln/InkScapeBoxMaker

**Comment by Michael-Breu-UIbk** [comment]
Hi all,

Thank you very much for updating for Inkscape 1.0.x.

I have merged the changes into the master repository.

I have also updated the extension in https://inkscape.org/~MichaelBreu/%E2%98%85box-maker-extension
